export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  // América del Norte
  "Estados Unidos": [
    "Nueva York",
    "Los Ángeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Filadelfia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San José",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Boston",
  ],
  Canadá: [
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec",
    "Hamilton",
    "Kitchener",
    "London",
    "Victoria",
    "Halifax",
    "Oshawa",
    "Windsor",
  ],
  México: [
    "Ciudad de México",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Juárez",
    "Zapopan",
    "Mérida",
    "San Luis Potosí",
    "Aguascalientes",
    "Hermosillo",
    "Saltillo",
    "Mexicali",
    "Culiacán",
    "Querétaro",
    "Chihuahua",
    "Morelia",
    "Cancún",
    "Veracruz",
  ],

  // América Central
  Guatemala: [
    "Ciudad de Guatemala",
    "Mixco",
    "Villa Nueva",
    "Petapa",
    "San Juan Sacatepéquez",
    "Quetzaltenango",
    "Villa Canales",
    "Escuintla",
    "Chinautla",
    "Chimaltenango",
  ],
  Belice: ["Ciudad de Belice", "San Ignacio", "Belmopan", "Orange Walk", "Dangriga", "Corozal", "San Pedro"],
  Honduras: [
    "Tegucigalpa",
    "San Pedro Sula",
    "Choloma",
    "La Ceiba",
    "El Progreso",
    "Villanueva",
    "Choluteca",
    "Comayagua",
    "Puerto Cortés",
    "La Lima",
  ],
  "El Salvador": [
    "San Salvador",
    "Soyapango",
    "Santa Ana",
    "San Miguel",
    "Mejicanos",
    "Apopa",
    "Delgado",
    "Sonsonate",
    "Ilopango",
    "Ahuachapán",
  ],
  Nicaragua: [
    "Managua",
    "León",
    "Masaya",
    "Matagalpa",
    "Chinandega",
    "Estelí",
    "Tipitapa",
    "Granada",
    "Jinotega",
    "Juigalpa",
  ],
  "Costa Rica": [
    "San José",
    "Limón",
    "San Francisco",
    "Alajuela",
    "Liberia",
    "Paraíso",
    "Puntarenas",
    "San Vicente",
    "San Isidro",
    "Curridabat",
  ],
  Panamá: [
    "Ciudad de Panamá",
    "San Miguelito",
    "Tocumen",
    "David",
    "Arraiján",
    "Colón",
    "Las Cumbres",
    "La Chorrera",
    "Pacora",
    "Santiago",
  ],

  // América del Sur
  Colombia: [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
    "Santa Marta",
    "Ibagué",
    "Pasto",
    "Manizales",
    "Neiva",
    "Villavicencio",
    "Armenia",
  ],
  Venezuela: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
    "Barcelona",
    "Maturín",
    "Puerto La Cruz",
    "Petare",
    "Turmero",
    "Ciudad Bolívar",
    "Mérida",
    "San Cristóbal",
    "Cumaná",
  ],
  Ecuador: [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Santo Domingo",
    "Machala",
    "Manta",
    "Portoviejo",
    "Loja",
    "Ambato",
    "Esmeraldas",
    "Quevedo",
    "Riobamba",
    "Milagro",
    "Ibarra",
    "La Libertad",
  ],
  Perú: [
    "Lima",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Piura",
    "Cusco",
    "Iquitos",
    "Huancayo",
    "Tacna",
    "Callao",
    "Chimbote",
    "Juliaca",
    "Ica",
    "Sullana",
    "Ayacucho",
    "Cajamarca",
    "Pucallpa",
    "Huánuco",
    "Tarapoto",
    "Chincha Alta",
  ],
  Brasil: [
    "São Paulo",
    "Río de Janeiro",
    "Brasilia",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaos",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Belém",
    "Goiânia",
    "Guarulhos",
    "Campinas",
    "São Luís",
    "São Gonçalo",
    "Maceió",
    "Duque de Caxias",
    "Natal",
    "Campo Grande",
  ],
  Bolivia: [
    "La Paz",
    "Santa Cruz de la Sierra",
    "Cochabamba",
    "Sucre",
    "Oruro",
    "Tarija",
    "Potosí",
    "Trinidad",
    "Cobija",
    "Riberalta",
  ],
  Paraguay: [
    "Asunción",
    "Ciudad del Este",
    "San Lorenzo",
    "Luque",
    "Capiatá",
    "Lambaré",
    "Fernando de la Mora",
    "Limpio",
    "Ñemby",
    "Encarnación",
  ],
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
    "Antofagasta",
    "Temuco",
    "Rancagua",
    "Talca",
    "Arica",
    "Puerto Montt",
    "Chillán",
    "Iquique",
    "Los Ángeles",
    "Coquimbo",
    "Osorno",
  ],
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "San Miguel de Tucumán",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Resistencia",
    "Corrientes",
    "Posadas",
    "Bahía Blanca",
    "Paraná",
  ],
  Uruguay: [
    "Montevideo",
    "Salto",
    "Paysandú",
    "Las Piedras",
    "Rivera",
    "Maldonado",
    "Tacuarembó",
    "Melo",
    "Mercedes",
    "Artigas",
  ],
  Guyana: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Rosignol"],
  Surinam: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam", "Mariënburg"],
  "Guyana Francesa": ["Cayena", "Saint-Laurent-du-Maroni", "Kourou", "Matoury", "Remire-Montjoly"],

  // Caribe
  Cuba: [
    "La Habana",
    "Santiago de Cuba",
    "Camagüey",
    "Holguín",
    "Guantánamo",
    "Santa Clara",
    "Las Tunas",
    "Bayamo",
    "Cienfuegos",
    "Pinar del Río",
  ],
  "República Dominicana": [
    "Santo Domingo",
    "Santiago de los Caballeros",
    "La Romana",
    "San Pedro de Macorís",
    "San Cristóbal",
    "Puerto Plata",
    "San Francisco de Macorís",
    "Higüey",
    "La Vega",
    "Moca",
  ],
  Haití: [
    "Puerto Príncipe",
    "Carrefour",
    "Delmas",
    "Cap-Haïtien",
    "Pétionville",
    "Gonaïves",
    "Saint-Marc",
    "Les Cayes",
    "Verrettes",
    "Port-de-Paix",
  ],
  Jamaica: [
    "Kingston",
    "Spanish Town",
    "Portmore",
    "Montego Bay",
    "May Pen",
    "Mandeville",
    "Old Harbour",
    "Savanna-la-Mar",
    "Ocho Rios",
    "Port Antonio",
  ],
  "Trinidad y Tobago": [
    "Puerto España",
    "Chaguanas",
    "San Fernando",
    "Port of Spain",
    "Arima",
    "Marabella",
    "Point Fortin",
    "Tunapuna",
    "San Juan",
    "Sangre Grande",
  ],
  Bahamas: ["Nassau", "Lucaya", "Freeport", "West End", "Cooper's Town", "Marsh Harbour", "Dunmore Town"],
  Barbados: ["Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane"],
  "Puerto Rico": [
    "San Juan",
    "Bayamón",
    "Carolina",
    "Ponce",
    "Caguas",
    "Guaynabo",
    "Mayagüez",
    "Trujillo Alto",
    "Arecibo",
    "Fajardo",
  ],
}

// Función helper para obtener ciudades de un país
export function getCitiesByCountry(countryName: string): string[] {
  return CITIES_BY_COUNTRY[countryName] || []
}
