import type { Order } from "@/types/order"
import type { Cliente } from "@/types/cliente"

export const mockOrders: Order[] = [
  {
    id: "SLE-2025022",
    estado: "Programado",
    etd: "09/02/2025",
    cliente: "North American Tile Group, LLC",
    proforma: "ORD-TEST-01",
    destino: "Dafeng (CNDFE), China",
    booking: "LMM0548354",
    tipo: "Marítimo",
  },
  {
    id: "SLE-2025022",
    estado: "Pendiente",
    etd: "09/02/2025",
    cliente: "North American Tile Group, LLC",
    proforma: "ORD-TEST-01",
    destino: "Dafeng (CNDFE), China",
    booking: "HMM0548354",
    tipo: "Marítimo",
  },
  {
    id: "SLE-2025022",
    estado: "Pendiente",
    etd: "09/02/2025",
    cliente: "North American Tile Group, LLC",
    proforma: "ORD-TEST-01",
    destino: "Dafeng (CNDFE), China",
    booking: "LMM0548354",
    tipo: "Aéreo",
  },
  {
    id: "SLE-2025022",
    estado: "Completado",
    etd: "09/02/2025",
    cliente: "North American Tile Group, LLC",
    proforma: "ORD-TEST-01",
    destino: "Dafeng (CNDFE), China",
    booking: "LMM0548354",
    tipo: "Marítimo",
  },
  {
    id: "SLE-2025023",
    estado: "Programado",
    etd: "10/02/2025",
    cliente: "Global Logistics Inc.",
    proforma: "ORD-TEST-02",
    destino: "Shanghai (CNSHA), China",
    booking: "MSC1234567",
    tipo: "Marítimo",
  },
  {
    id: "SLE-2025024",
    estado: "Pendiente",
    etd: "11/02/2025",
    cliente: "Pacific Trade Co.",
    proforma: "ORD-TEST-03",
    destino: "Los Angeles (USLAX), USA",
    booking: "CMA9876543",
    tipo: "Aéreo",
  },
  {
    id: "SLE-2025025",
    estado: "Completado",
    etd: "08/02/2025",
    cliente: "Euro Shipping Ltd.",
    proforma: "ORD-TEST-04",
    destino: "Rotterdam (NLRTM), Netherlands",
    booking: "HAP5551234",
    tipo: "Marítimo",
  },
  {
    id: "SLE-2025026",
    estado: "Programado",
    etd: "12/02/2025",
    cliente: "Asian Imports LLC",
    proforma: "ORD-TEST-05",
    destino: "Singapore (SGSIN), Singapore",
    booking: "ONE7778899",
    tipo: "Terrestre",
  },
  {
    id: "SLE-2025027",
    estado: "Pendiente",
    etd: "13/02/2025",
    cliente: "South American Traders",
    proforma: "ORD-TEST-06",
    destino: "Santos (BRSSZ), Brazil",
    booking: "EVG3334455",
    tipo: "Marítimo",
  },
  {
    id: "SLE-2025028",
    estado: "Completado",
    etd: "07/02/2025",
    cliente: "Mediterranean Cargo SA",
    proforma: "ORD-TEST-07",
    destino: "Barcelona (ESBCN), Spain",
    booking: "MSK6667788",
    tipo: "Aéreo",
  },
]

export const mockClientes: Cliente[] = [
  {
    id: "CLI-001",
    pais: "Estados Unidos",
    ruc: "20-1234567",
    eori: "US123456789",
    empresa: "North American Tile Group, LLC",
    direccionCalle: "5th Avenue",
    direccionNumero: "1250",
    ciudad: "New York",
    zipCode: "10001",
    contacto: "John Smith",
    telefono: "+1 212-555-0123",
    email: "john.smith@natg.com",
    estado: "Activo",
    notifies: [
      {
        id: "NOT-001",
        empresaNotify: "NATG Warehouse Services",
        pais: "Estados Unidos",
        ruc: "20-7654321",
        direccion: "Industrial Park, Building 5",
        ciudad: "Newark",
        zipCode: "07102",
        contacto: "Sarah Johnson",
        telefono: "+1 973-555-0456",
        email: "sarah.j@natgwarehouse.com",
      },
    ],
  },
  {
    id: "CLI-002",
    pais: "Países Bajos",
    ruc: "NL123456789B01",
    eori: "NL123456789",
    empresa: "Euro Shipping Ltd.",
    direccionCalle: "Havenstraat",
    direccionNumero: "45",
    ciudad: "Rotterdam",
    zipCode: "3011 AB",
    contacto: "Hans Mueller",
    telefono: "+31 10-555-0789",
    email: "h.mueller@euroshipping.nl",
    estado: "Activo",
    notifies: [
      {
        id: "NOT-002",
        empresaNotify: "Euro Logistics Center",
        pais: "Países Bajos",
        ruc: "NL987654321B01",
        direccion: "Logistics Avenue 12",
        ciudad: "Amsterdam",
        zipCode: "1012 AB",
        contacto: "Maria van Berg",
        telefono: "+31 20-555-0321",
        email: "m.vanberg@eurologistics.nl",
      },
    ],
  },
  {
    id: "CLI-003",
    pais: "Brasil",
    ruc: "12.345.678/0001-90",
    empresa: "South American Traders",
    direccionCalle: "Avenida Paulista",
    direccionNumero: "1578",
    ciudad: "São Paulo",
    zipCode: "01310-200",
    contacto: "Carlos Silva",
    telefono: "+55 11-3456-7890",
    email: "carlos.silva@satraders.com.br",
    estado: "Activo",
    notifies: [],
  },
  {
    id: "CLI-004",
    pais: "Singapur",
    ruc: "201234567K",
    eori: "SG201234567K",
    empresa: "Asian Imports LLC",
    direccionCalle: "Marina Boulevard",
    direccionNumero: "8",
    ciudad: "Singapore",
    zipCode: "018981",
    contacto: "Wei Zhang",
    telefono: "+65 6234-5678",
    email: "w.zhang@asianimports.sg",
    estado: "Activo",
    notifies: [
      {
        id: "NOT-003",
        empresaNotify: "Singapore Distribution Hub",
        pais: "Singapur",
        ruc: "202345678L",
        direccion: "Jurong Port Road 37",
        ciudad: "Singapore",
        zipCode: "619110",
        contacto: "Li Mei",
        telefono: "+65 6345-6789",
        email: "li.mei@sghub.sg",
      },
    ],
  },
  {
    id: "CLI-005",
    pais: "España",
    ruc: "B12345678",
    eori: "ESB12345678",
    empresa: "Mediterranean Cargo SA",
    direccionCalle: "Paseo de Gracia",
    direccionNumero: "92",
    ciudad: "Barcelona",
    zipCode: "08008",
    contacto: "Isabel García",
    telefono: "+34 93-456-7890",
    email: "i.garcia@medcargo.es",
    estado: "Inactivo",
    notifies: [],
  },
  {
    id: "CLI-006",
    pais: "China",
    ruc: "91310000123456789X",
    empresa: "Pacific Trade Co.",
    direccionCalle: "Nanjing Road",
    direccionNumero: "1000",
    ciudad: "Shanghai",
    zipCode: "200001",
    contacto: "Liu Wei",
    telefono: "+86 21-6234-5678",
    email: "liu.wei@pactrade.cn",
    estado: "Activo",
    notifies: [
      {
        id: "NOT-004",
        empresaNotify: "Shanghai Freight Forwarders",
        pais: "China",
        ruc: "91310000987654321Y",
        direccion: "Pudong Avenue 500",
        ciudad: "Shanghai",
        zipCode: "200120",
        contacto: "Chen Ming",
        telefono: "+86 21-5876-5432",
        email: "chen.ming@shfreight.cn",
      },
      {
        id: "NOT-005",
        empresaNotify: "Beijing Import Services",
        pais: "China",
        ruc: "91110000456789123Z",
        direccion: "Chaoyang District, Building 8",
        ciudad: "Beijing",
        zipCode: "100020",
        contacto: "Wang Fang",
        telefono: "+86 10-8765-4321",
        email: "wang.fang@bjimport.cn",
      },
    ],
  },
]
