import type { Proveedor } from "@/types/proveedor"

export const mockProveedores: Proveedor[] = [
  {
    id: "PROV-001",
    pais: "Perú",
    ruc: "20123456789",
    empresa: "Logística Express SAC",
    direccionCalle: "Av. El Derby",
    direccionNumero: "254",
    ciudad: "Lima",
    region: "Lima",
    zipCode: "15036",
    contacto: "Carlos Mendoza",
    telefono: "+51 1-234-5678",
    email: "carlos.mendoza@logexpress.pe",
    tiposProveedor: ["Agencia de Carga", "Operador Logístico"],
    estado: "Activo",
  },
  {
    id: "PROV-002",
    pais: "Estados Unidos",
    ruc: "20-9876543",
    empresa: "Global Freight Services LLC",
    direccionCalle: "Main Street",
    direccionNumero: "1500",
    ciudad: "Miami",
    region: "Florida",
    zipCode: "33101",
    contacto: "Jennifer Smith",
    telefono: "+1 305-555-0123",
    email: "j.smith@globalfreight.com",
    tiposProveedor: ["Agencia de Carga", "Transporte"],
    estado: "Activo",
  },
  {
    id: "PROV-003",
    pais: "China",
    ruc: "91310000123456789X",
    empresa: "Shanghai Customs Broker Co.",
    direccionCalle: "Pudong Avenue",
    direccionNumero: "888",
    ciudad: "Shanghai",
    zipCode: "200120",
    contacto: "Li Wei",
    telefono: "+86 21-6234-5678",
    email: "li.wei@shcustoms.cn",
    tiposProveedor: ["Agencia de Aduana"],
    estado: "Activo",
  },
  {
    id: "PROV-004",
    pais: "España",
    ruc: "B87654321",
    empresa: "Transportes Ibéricos SA",
    direccionCalle: "Calle Mayor",
    direccionNumero: "45",
    ciudad: "Madrid",
    region: "Madrid",
    zipCode: "28013",
    contacto: "Miguel Rodríguez",
    telefono: "+34 91-555-0789",
    email: "m.rodriguez@transibericos.es",
    tiposProveedor: ["Transporte", "Operador Logístico"],
    estado: "Activo",
  },
  {
    id: "PROV-005",
    pais: "Brasil",
    ruc: "12.345.678/0001-90",
    empresa: "Santos Port Services Ltda",
    direccionCalle: "Avenida Atlântica",
    direccionNumero: "2000",
    ciudad: "Santos",
    region: "São Paulo",
    zipCode: "11010-100",
    contacto: "Ana Silva",
    telefono: "+55 13-3456-7890",
    email: "ana.silva@santosport.com.br",
    tiposProveedor: ["Agencia de Carga", "Agencia de Aduana", "Operador Logístico"],
    estado: "Inactivo",
  },
  {
    id: "PROV-006",
    pais: "Países Bajos",
    ruc: "NL123456789B01",
    empresa: "Rotterdam Logistics BV",
    direccionCalle: "Havenstraat",
    direccionNumero: "100",
    ciudad: "Rotterdam",
    zipCode: "3011 AB",
    contacto: "Hans van der Berg",
    telefono: "+31 10-555-0456",
    email: "h.vandenberg@rotterdamlog.nl",
    tiposProveedor: ["Operador Logístico", "Transporte"],
    estado: "Activo",
  },
]
