import type { Producto } from "@/types/producto"

export const mockProductos: Producto[] = [
  {
    id: "PROD-001",
    codigo_producto: "ARZ-BL-001",
    descripcion_comercial: "Arroz Blanco Premium",
    formato_comercial: "Saco 50kg",
    unidades_comerciales_valor: 50,
    unidad: "kg",
    pais_origen: "Perú",
    hs_code: "1006.30.00",
    empaque_base: "Saco",
    peso_neto_kg: 50,
    peso_bruto_kg: 51,
    dimensiones_cm: "80 x 50 x 15",
    precio_fob_usd: 45.5,
    empaque_secundario: "Paleta",
    cantidad_maxima_empaque_secundario: 40,
    estado: "Activo",
  },
  {
    id: "PROD-002",
    codigo_producto: "CAF-ORG-002",
    descripcion_comercial: "Café Orgánico Grano",
    formato_comercial: "Saco 60kg",
    unidades_comerciales_valor: 60,
    unidad: "kg",
    pais_origen: "Colombia",
    hs_code: "0901.11.00",
    empaque_base: "Saco",
    peso_neto_kg: 60,
    peso_bruto_kg: 61.5,
    dimensiones_cm: "90 x 60 x 20",
    precio_fob_usd: 320.0,
    empaque_secundario: "Paleta",
    cantidad_maxima_empaque_secundario: 30,
    estado: "Activo",
  },
  {
    id: "PROD-003",
    codigo_producto: "AZU-REF-003",
    descripcion_comercial: "Azúcar Refinada",
    formato_comercial: "Big Bag 1000kg",
    unidades_comerciales_valor: 1000,
    unidad: "kg",
    pais_origen: "Perú",
    hs_code: "1701.99.00",
    empaque_base: "Big bag",
    peso_neto_kg: 1000,
    peso_bruto_kg: 1005,
    dimensiones_cm: "110 x 110 x 180",
    precio_fob_usd: 580.0,
    empaque_secundario: "Big bag",
    cantidad_maxima_empaque_secundario: 1,
    estado: "Activo",
  },
  {
    id: "PROD-004",
    codigo_producto: "QUI-IND-004",
    descripcion_comercial: "Quinua Blanca",
    formato_comercial: "Saco 25kg",
    unidades_comerciales_valor: 25,
    unidad: "kg",
    pais_origen: "Perú",
    hs_code: "1008.50.00",
    empaque_base: "Saco",
    peso_neto_kg: 25,
    peso_bruto_kg: 25.5,
    dimensiones_cm: "60 x 40 x 12",
    precio_fob_usd: 95.0,
    empaque_secundario: "Paleta",
    cantidad_maxima_empaque_secundario: 48,
    estado: "Activo",
  },
  {
    id: "PROD-005",
    codigo_producto: "MAD-TER-005",
    descripcion_comercial: "Madera Terciada",
    formato_comercial: "Plancha 2.44 x 1.22m",
    unidades_comerciales_valor: 2.98,
    unidad: "m²",
    pais_origen: "Chile",
    hs_code: "4412.31.00",
    empaque_base: "Pallet",
    peso_neto_kg: 45,
    peso_bruto_kg: 48,
    dimensiones_cm: "244 x 122 x 1.8",
    precio_fob_usd: 28.5,
    empaque_secundario: "Paleta",
    cantidad_maxima_empaque_secundario: 50,
    estado: "Activo",
  },
  {
    id: "PROD-006",
    codigo_producto: "ACE-OLI-006",
    descripcion_comercial: "Aceite de Oliva Extra Virgen",
    formato_comercial: "Tambor 200L",
    unidades_comerciales_valor: 200,
    unidad: "litro",
    pais_origen: "Chile",
    hs_code: "1509.10.00",
    empaque_base: "Tambor",
    peso_neto_kg: 184,
    peso_bruto_kg: 195,
    dimensiones_cm: "60 x 60 x 90",
    precio_fob_usd: 1850.0,
    empaque_secundario: "Unidad",
    cantidad_maxima_empaque_secundario: 1,
    estado: "Activo",
  },
  {
    id: "PROD-007",
    codigo_producto: "FRU-DES-007",
    descripcion_comercial: "Mango Deshidratado",
    formato_comercial: "Caja 10kg",
    unidades_comerciales_valor: 10,
    unidad: "kg",
    pais_origen: "Perú",
    hs_code: "0804.50.20",
    empaque_base: "Caja",
    peso_neto_kg: 10,
    peso_bruto_kg: 10.8,
    dimensiones_cm: "40 x 30 x 25",
    precio_fob_usd: 125.0,
    empaque_secundario: "Paleta",
    cantidad_maxima_empaque_secundario: 80,
    estado: "Activo",
  },
  {
    id: "PROD-008",
    codigo_producto: "CEM-GRI-008",
    descripcion_comercial: "Cemento Gris Portland",
    formato_comercial: "Saco 42.5kg",
    unidades_comerciales_valor: 42.5,
    unidad: "kg",
    pais_origen: "Colombia",
    hs_code: "2523.29.00",
    empaque_base: "Saco",
    peso_neto_kg: 42.5,
    peso_bruto_kg: 43,
    dimensiones_cm: "70 x 45 x 12",
    precio_fob_usd: 8.5,
    empaque_secundario: "Paleta",
    cantidad_maxima_empaque_secundario: 56,
    estado: "Inactivo",
  },
]
