import type { Container } from "@/types/container"

export const mockContainers: Container[] = [
  {
    id: "1",
    numero: "MNBU3331011",
    iso: "20DT",
    tara: "2450",
    precintos: ["LLSKO0001", "ADU001111"],
    estadoActual: "En Tránsito",
    milestones: [
      {
        id: "1",
        type: "deposito_vacios_origen",
        titulo: "Terminal Portuario del Callao",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0618, lng: -77.1423 },
      },
      {
        id: "2",
        type: "planta_origen",
        titulo: "Planta",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0564, lng: -77.1528 },
      },
      {
        id: "3",
        type: "deposito_extraportuario_origen",
        titulo: "Depósito Extraportuario",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        detalles: "EVER LAWFUL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0664, lng: -77.1628 },
      },
      {
        id: "4",
        type: "puerto_origen",
        titulo: "Puerto",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0464, lng: -77.1428 },
      },
      {
        id: "5",
        type: "nave_1",
        titulo: "Carga a Nave",
        ubicacion: "Shanghai",
        codigoPuerto: "CNSHG",
        detalles: "EVER LAWFUL",
        fecha: "Jul 19",
        status: "en_progreso",
        coordenadas: { lat: 31.2304, lng: 121.4737 },
      },
      {
        id: "6",
        type: "puerto_destino",
        titulo: "Puerto de Destino",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        fecha: "Aug 15",
        status: "estimado",
        coordenadas: { lat: 33.2, lng: 120.5 },
      },
      {
        id: "7",
        type: "planta_destino",
        titulo: "Planta",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.21, lng: 120.51 },
      },
      {
        id: "8",
        type: "deposito_vacios_destino",
        titulo: "Depósito de Vacíos",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.22, lng: 120.52 },
      },
    ],
  },
  {
    id: "2",
    numero: "MNBU3331012",
    iso: "20DT",
    tara: "2450",
    precintos: ["LLSKO0002", "ADU001112"],
    estadoActual: "En Tránsito",
    milestones: [
      {
        id: "1",
        type: "deposito_vacios_origen",
        titulo: "Av. Argentina con Faucett",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0485, lng: -77.0967 },
      },
      {
        id: "2",
        type: "planta_origen",
        titulo: "Planta",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0564, lng: -77.1528 },
      },
      {
        id: "3",
        type: "deposito_extraportuario_origen",
        titulo: "Depósito Extraportuario",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        detalles: "EVER LAWFUL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0664, lng: -77.1628 },
      },
      {
        id: "4",
        type: "puerto_origen",
        titulo: "Puerto",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 30 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0464, lng: -77.1428 },
      },
      {
        id: "5",
        type: "nave_1",
        titulo: "Carga a Nave",
        ubicacion: "Shanghai",
        codigoPuerto: "CNSHG",
        detalles: "EVER LAWFUL",
        fecha: "Jul 19",
        status: "en_progreso",
        coordenadas: { lat: 31.2304, lng: 121.4737 },
      },
      {
        id: "6",
        type: "puerto_destino",
        titulo: "Puerto de Destino",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        fecha: "Aug 15",
        status: "estimado",
        coordenadas: { lat: 33.2, lng: 120.5 },
      },
      {
        id: "7",
        type: "planta_destino",
        titulo: "Planta",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.21, lng: 120.51 },
      },
      {
        id: "8",
        type: "deposito_vacios_destino",
        titulo: "Depósito de Vacíos",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.22, lng: 120.52 },
      },
    ],
  },
  {
    id: "3",
    numero: "MNBU3331013",
    iso: "40HC",
    tara: "3900",
    precintos: ["LLSKO0003", "ADU001113"],
    estadoActual: "En Tránsito",
    milestones: [
      {
        id: "1",
        type: "deposito_vacios_origen",
        titulo: "Ciudad del Pescador",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 29 08:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0702, lng: -77.1319 },
      },
      {
        id: "2",
        type: "planta_origen",
        titulo: "Planta",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 29 10:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0564, lng: -77.1528 },
      },
      {
        id: "3",
        type: "deposito_extraportuario_origen",
        titulo: "Depósito Extraportuario",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        detalles: "MAERSK LINE",
        fecha: "May 29 02:00 PM",
        status: "completado",
        coordenadas: { lat: -12.0664, lng: -77.1628 },
      },
      {
        id: "4",
        type: "puerto_origen",
        titulo: "Puerto",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 30 06:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0464, lng: -77.1428 },
      },
      {
        id: "5",
        type: "nave_1",
        titulo: "Carga a Nave",
        ubicacion: "Shanghai",
        codigoPuerto: "CNSHG",
        detalles: "MAERSK LINE",
        fecha: "Jul 18",
        status: "en_progreso",
        coordenadas: { lat: 31.2304, lng: 121.4737 },
      },
      {
        id: "6",
        type: "puerto_destino",
        titulo: "Puerto de Destino",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        fecha: "Aug 14",
        status: "estimado",
        coordenadas: { lat: 33.2, lng: 120.5 },
      },
      {
        id: "7",
        type: "planta_destino",
        titulo: "Planta",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.21, lng: 120.51 },
      },
      {
        id: "8",
        type: "deposito_vacios_destino",
        titulo: "Depósito de Vacíos",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.22, lng: 120.52 },
      },
    ],
  },
  {
    id: "4",
    numero: "MNBU3331014",
    iso: "20DT",
    tara: "2450",
    precintos: ["LLSKO0004", "ADU001114", "SEAL9999"],
    estadoActual: "En Puerto",
    milestones: [
      {
        id: "1",
        type: "deposito_vacios_origen",
        titulo: "La Punta (zona costera)",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 28 07:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0728, lng: -77.1675 },
      },
      {
        id: "2",
        type: "planta_origen",
        titulo: "Planta",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 28 11:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0564, lng: -77.1528 },
      },
      {
        id: "3",
        type: "deposito_extraportuario_origen",
        titulo: "Depósito Extraportuario",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        detalles: "CMA CGM",
        fecha: "May 28 04:00 PM",
        status: "completado",
        coordenadas: { lat: -12.0664, lng: -77.1628 },
      },
      {
        id: "4",
        type: "puerto_origen",
        titulo: "Puerto",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 29 08:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0464, lng: -77.1428 },
      },
      {
        id: "5",
        type: "nave_1",
        titulo: "Carga a Nave",
        ubicacion: "Shanghai",
        codigoPuerto: "CNSHG",
        detalles: "CMA CGM",
        fecha: "Jul 17",
        status: "completado",
        coordenadas: { lat: 31.2304, lng: 121.4737 },
      },
      {
        id: "6",
        type: "puerto_destino",
        titulo: "Puerto de Destino",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        fecha: "Aug 13",
        status: "en_progreso",
        coordenadas: { lat: 33.2, lng: 120.5 },
      },
      {
        id: "7",
        type: "planta_destino",
        titulo: "Planta",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.21, lng: 120.51 },
      },
      {
        id: "8",
        type: "deposito_vacios_destino",
        titulo: "Depósito de Vacíos",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.22, lng: 120.52 },
      },
    ],
  },
  {
    id: "5",
    numero: "MNBU3331015",
    iso: "40HC",
    tara: "3900",
    precintos: ["LLSKO0005", "ADU001115"],
    estadoActual: "En Tránsito",
    milestones: [
      {
        id: "1",
        type: "deposito_vacios_origen",
        titulo: "Av. Guardia Chalaca con Colonial",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 31 09:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0534, lng: -77.1132 },
      },
      {
        id: "2",
        type: "planta_origen",
        titulo: "Planta",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "May 31 01:00 PM",
        status: "completado",
        coordenadas: { lat: -12.0564, lng: -77.1528 },
      },
      {
        id: "3",
        type: "deposito_extraportuario_origen",
        titulo: "Depósito Extraportuario",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        detalles: "HAPAG LLOYD",
        fecha: "May 31 05:00 PM",
        status: "completado",
        coordenadas: { lat: -12.0664, lng: -77.1628 },
      },
      {
        id: "4",
        type: "puerto_origen",
        titulo: "Puerto",
        ubicacion: "Callao",
        codigoPuerto: "PECLL",
        fecha: "Jun 01 07:00 AM",
        status: "completado",
        coordenadas: { lat: -12.0464, lng: -77.1428 },
      },
      {
        id: "5",
        type: "nave_1",
        titulo: "Carga a Nave",
        ubicacion: "Shanghai",
        codigoPuerto: "CNSHG",
        detalles: "HAPAG LLOYD",
        fecha: "Jul 20",
        status: "estimado",
        coordenadas: { lat: 31.2304, lng: 121.4737 },
      },
      {
        id: "6",
        type: "puerto_destino",
        titulo: "Puerto de Destino",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        fecha: "Aug 16",
        status: "estimado",
        coordenadas: { lat: 33.2, lng: 120.5 },
      },
      {
        id: "7",
        type: "planta_destino",
        titulo: "Planta",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.21, lng: 120.51 },
      },
      {
        id: "8",
        type: "deposito_vacios_destino",
        titulo: "Depósito de Vacíos",
        ubicacion: "Dafeng",
        codigoPuerto: "CNDFE",
        status: "pendiente",
        coordenadas: { lat: 33.22, lng: 120.52 },
      },
    ],
  },
]
